version: '3'
services:
  postal:
    image: emergya/postal:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    ports:
      - "25:25"
      #- "80:80"
      #- "2525:2525"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ${DATA_DIR}/docker-containers-volumes/var/lib/mysql:/var/lib/mysql
      - ${DATA_DIR}/docker-containers-volumes/var/log/nginx:/var/log/nginx
      - ${DATA_DIR}/docker-containers-volumes/opt/postal/app/log:/opt/postal/app/log
      - ${DATA_DIR}/docker-containers-volumes/opt/postal/app/public:/opt/postal/app/public
      - ${DATA_DIR}/docker-containers-volumes/opt/postal/config:/opt/postal/config

